# Generated by Django 4.1.4 on 2022-12-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='MobileArt name')),
                ('name1', models.CharField(max_length=50, verbose_name='MobileArt name1')),
                ('about', models.TextField(verbose_name='MobileArt about')),
                ('about1', models.TextField(verbose_name='MobileArt about')),
                ('img', models.ImageField(upload_to='media', verbose_name='MobileArt image')),
            ],
            options={
                'verbose_name': 'MobileArt',
                'verbose_name_plural': 'MobileArts',
            },
        ),
    ]
