# Generated by Django 4.1.4 on 2022-12-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_mobileart_name1_mobileart_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobileart',
            name='about2',
        ),
        migrations.AddField(
            model_name='mobileart',
            name='name1',
            field=models.CharField(max_length=50, null=True, verbose_name='MobileArt name1'),
        ),
    ]
