# Generated by Django 4.1.4 on 2022-12-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_mobileart_about2_mobileart_name1'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='HomeBody name')),
                ('about', models.TextField(verbose_name='HomeBody about')),
            ],
            options={
                'verbose_name': 'HomeBody',
                'verbose_name_plural': 'HomeBodies',
            },
        ),
    ]
