# Generated by Django 4.1.4 on 2022-12-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_homefoot'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootHomeFoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='FootHomeFoot about')),
            ],
            options={
                'verbose_name': 'FootHomeFoot',
                'verbose_name_plural': 'FootHomeFoots',
            },
        ),
    ]
