# Generated by Django 4.1.4 on 2022-12-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_aboutparallo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='AboutAbout name')),
            ],
            options={
                'verbose_name': 'AboutAbout',
                'verbose_name_plural': 'AboutAbouts',
            },
        ),
    ]
