# Generated by Django 4.1.4 on 2022-12-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_aboutabout'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='AboutQuality name')),
                ('about', models.TextField(verbose_name='AboutQuality about')),
            ],
            options={
                'verbose_name': 'AboutQuality',
                'verbose_name_plural': 'AboutQualities',
            },
        ),
    ]
