# Generated by Django 4.1.4 on 2022-12-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_aboutquality_about1'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutquality',
            name='number',
            field=models.IntegerField(default=0, verbose_name='AboutQuality number'),
        ),
    ]
