# Generated by Django 4.1.4 on 2022-12-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_aboutfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutFoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='AboutFoot name')),
                ('about', models.TextField(verbose_name='AboutFoot about')),
            ],
            options={
                'verbose_name': 'AboutFoot',
                'verbose_name_plural': 'AboutFoots',
            },
        ),
    ]
