# Generated by Django 4.1.4 on 2022-12-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_aboutfoot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='AboutImage image')),
            ],
            options={
                'verbose_name': 'AboutImage',
                'verbose_name_plural': 'AboutImages',
            },
        ),
    ]
