# Generated by Django 4.1.4 on 2022-12-29 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_serviceparallo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceParallo',
            new_name='ServicesParallo',
        ),
        migrations.AlterModelOptions(
            name='servicesparallo',
            options={'verbose_name': 'ServicesParallo', 'verbose_name_plural': 'ServicesParallos'},
        ),
    ]
