# Generated by Django 4.1.4 on 2022-12-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_servicesimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='OurServices name')),
                ('about', models.TextField(verbose_name='OurServices about')),
                ('about1', models.TextField(verbose_name='OurServices about1')),
                ('about2', models.TextField(verbose_name='OurServices about2')),
                ('img', models.ImageField(upload_to='media', verbose_name='OurServices image')),
            ],
            options={
                'verbose_name': 'OurServices',
                'verbose_name_plural': 'OurServices',
            },
        ),
    ]
