# Generated by Django 4.1.4 on 2022-12-30 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_ourservices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourservices',
            name='about1',
        ),
        migrations.RemoveField(
            model_name='ourservices',
            name='about2',
        ),
    ]
