# Generated by Django 4.1.4 on 2022-12-30 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_ourservices_about1_remove_ourservices_about2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourservices',
            options={'verbose_name': 'OurServices', 'verbose_name_plural': 'OurServiceses'},
        ),
    ]
