# Generated by Django 4.1.4 on 2022-12-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_ourservices_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='ServicesBody about')),
                ('about1', models.TextField(verbose_name='ServicesBody about1')),
            ],
            options={
                'verbose_name': 'ServicesBody',
                'verbose_name_plural': 'ServicesBodies',
            },
        ),
    ]
