# Generated by Django 4.1.4 on 2022-12-30 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_servicesfoot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesfoot',
            name='about1',
        ),
        migrations.RemoveField(
            model_name='servicesfoot',
            name='about2',
        ),
        migrations.RemoveField(
            model_name='servicesfoot',
            name='name1',
        ),
        migrations.RemoveField(
            model_name='servicesfoot',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='servicesfoot',
            name='name3',
        ),
        migrations.RemoveField(
            model_name='servicesfoot',
            name='name4',
        ),
        migrations.RemoveField(
            model_name='servicesfoot',
            name='name5',
        ),
    ]
