# Generated by Django 4.1.4 on 2022-12-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_servicesfoot_about1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesfoot',
            name='about1',
            field=models.TextField(null=True, verbose_name='ServicesFoot about1'),
        ),
    ]
