# Generated by Django 4.1.4 on 2022-12-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_servicessubfoot'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicessubfoot',
            name='about1',
            field=models.TextField(null=True, verbose_name='ServicesSubFoot about1'),
        ),
    ]
