# Generated by Django 4.1.4 on 2022-12-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_servicessubfoot_about1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicesSubFoot',
        ),
        migrations.AddField(
            model_name='servicesfoot',
            name='about',
            field=models.TextField(null=True, verbose_name='ServicesFoot about'),
        ),
        migrations.AddField(
            model_name='servicesfoot',
            name='about1',
            field=models.TextField(null=True, verbose_name='ServicesFoot about1'),
        ),
        migrations.AddField(
            model_name='servicesfoot',
            name='name3',
            field=models.CharField(max_length=50, null=True, verbose_name='ServicesFoot name3'),
        ),
        migrations.AlterField(
            model_name='servicesfoot',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='ServicesFoot name'),
        ),
    ]
