# Generated by Django 4.1.4 on 2022-12-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_delete_servicessubfoot_servicesfoot_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesfoot',
            name='about2',
            field=models.TextField(null=True, verbose_name='ServicesFoot about2'),
        ),
        migrations.AddField(
            model_name='servicesfoot',
            name='about3',
            field=models.TextField(null=True, verbose_name='ServicesFoot about3'),
        ),
        migrations.AddField(
            model_name='servicesfoot',
            name='about4',
            field=models.TextField(null=True, verbose_name='ServicesFoot about4'),
        ),
        migrations.AddField(
            model_name='servicesfoot',
            name='about5',
            field=models.TextField(null=True, verbose_name='ServicesFoot about5'),
        ),
        migrations.AddField(
            model_name='servicesfoot',
            name='name4',
            field=models.CharField(max_length=50, null=True, verbose_name='ServicesFoot name4'),
        ),
        migrations.AddField(
            model_name='servicesfoot',
            name='name5',
            field=models.CharField(max_length=50, null=True, verbose_name='ServicesFoot name5'),
        ),
    ]
