# Generated by Django 4.1.4 on 2022-12-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_servicesfoot_about2_servicesfoot_about3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialsParallo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='TestimonialsParallo name')),
                ('name1', models.CharField(max_length=30, verbose_name='TestimonialsParallo name1')),
                ('name2', models.CharField(max_length=30, verbose_name='TestimonialsParallo name2')),
                ('name3', models.CharField(max_length=30, verbose_name='TestimonialsParallo name3')),
                ('name4', models.CharField(max_length=30, verbose_name='TestimonialsParallo name4')),
                ('name5', models.CharField(max_length=30, verbose_name='TestimonialsParallo name5')),
                ('about', models.TextField(verbose_name='TestimonialsParallo about')),
            ],
            options={
                'verbose_name': 'TestimonialParallo',
                'verbose_name_plural': 'TestimonialParallos',
            },
        ),
    ]
