# Generated by Django 4.1.4 on 2022-12-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_testimonialsparallo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='TestimonialsImage image')),
            ],
            options={
                'verbose_name': 'TestimonialsImage',
                'verbose_name_plural': 'TestimonialsImages',
            },
        ),
    ]
