# Generated by Django 4.1.4 on 2022-12-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_testimonialsimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Testimonials name')),
                ('about', models.TextField(verbose_name='Testimonials about')),
                ('img', models.ImageField(upload_to='media', verbose_name='Testimonials image')),
            ],
            options={
                'verbose_name': 'Testimonials',
                'verbose_name_plural': 'Testimonialses',
            },
        ),
    ]
