# Generated by Django 4.1.4 on 2022-12-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialsBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='TestimonialsBody name')),
                ('about', models.TextField(verbose_name='TestimonialsBody about')),
                ('img', models.ImageField(upload_to='media', verbose_name='TestimonialsBody image')),
            ],
            options={
                'verbose_name': 'TestimonialsBody',
                'verbose_name_plural': 'TestimonialsBodies',
            },
        ),
    ]
