# Generated by Django 4.1.4 on 2022-12-30 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_testimonialsbody_about1_testimonialsbody_img1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonialsbody',
            name='about1',
        ),
        migrations.RemoveField(
            model_name='testimonialsbody',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='testimonialsbody',
            name='name1',
        ),
    ]
