# Generated by Django 4.1.4 on 2022-12-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_testimonialsbody_about1_testimonialsbody_about2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialsFoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='TestimonialsFoot name')),
                ('about', models.TextField(verbose_name='TestimonialsFoot about')),
                ('about1', models.TextField(verbose_name='TestimonialsFoot about1')),
                ('img', models.ImageField(upload_to='media', verbose_name='TestimonialsFoot image')),
            ],
            options={
                'verbose_name': 'TestimonialsFoot',
                'verbose_name_plural': 'TestimonialsFoots',
            },
        ),
    ]
