# Generated by Django 4.1.4 on 2022-12-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='img',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Contact image'),
        ),
    ]
