# Generated by Django 4.1.4 on 2022-12-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_contactbody'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactbody',
            name='about1',
        ),
        migrations.RemoveField(
            model_name='contactbody',
            name='name',
        ),
    ]
