# Generated by Django 4.1.4 on 2022-12-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_remove_contactbody_about1_remove_contactbody_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ContactBodi name')),
                ('about', models.TextField(verbose_name='ContactBodi about')),
                ('about1', models.TextField(verbose_name='ContactBodi about1')),
            ],
            options={
                'verbose_name': 'ContactBodi',
                'verbose_name_plural': 'ContactBodis',
            },
        ),
    ]
