# Generated by Django 4.1.4 on 2022-12-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_contactbodi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ContactFoot name')),
                ('about', models.TextField(verbose_name='ContactFoot about')),
                ('about1', models.TextField(verbose_name='ContactFoot about1')),
            ],
            options={
                'verbose_name': 'ContactFoot',
                'verbose_name_plural': 'ContactFoot',
            },
        ),
    ]
