# Generated by Django 4.1.4 on 2023-01-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_contactfoot_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonialsbody',
            name='about1',
        ),
        migrations.RemoveField(
            model_name='testimonialsbody',
            name='about2',
        ),
        migrations.RemoveField(
            model_name='testimonialsbody',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='testimonialsbody',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='testimonialsbody',
            name='name1',
        ),
        migrations.RemoveField(
            model_name='testimonialsbody',
            name='name2',
        ),
    ]
